
FROM python:3.9-slim-buster

RUN mkdir /optimiser
WORKDIR /optimiser
ADD . /optimiser/
RUN pip install -r requirements.txt

EXPOSE 5000
ENTRYPOINT ["python3", "/optimiser/optimiser.py"]
CMD ["http://0.0.0.0:5001/tests/endpoint"]