apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-pv-claim
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile
---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: azurefile-csi
# provisioner: file.csi.azure.com
# allowVolumeExpansion: true
# parameters:
#   skuName: Standard_LRS  # available values: Premium_LRS, Premium_ZRS, Standard_LRS, Standard_GRS, Standard_ZRS, Standard_RAGRS, Standard_RAGZRS
# reclaimPolicy: Retain
# volumeBindingMode: Immediate
# mountOptions:
#   - dir_mode=0777
#   - file_mode=0777
#   - mfsymlinks
#   - cache=strict  # https://linux.die.net/man/8/mount.cifs
#   - nosharesock  # reduce probability of reconnect race
#   - actimeo=30  # reduce latency for metadata-heavy workload