apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: argo
  name: argo-pv-claim
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi