apiVersion: v1
kind: Pod
metadata:
  name: sbo
  namespace: argo
spec:
  volumes:
    - name: argo-pv-volume
      persistentVolumeClaim:
        claimName: argo-pv-claim
  containers:
    - name: sbo-container
      image: lukeraphael/sbo
      imagePullPolicy: IfNotPresent
      command: ["python3", "parallelisation.py", "--n_gen", "10", "--workers", "10", "--pop_size", "80", "--choice", "kubernetes"]
      volumeMounts:
        - mountPath: "/minifab/"
          name: argo-pv-volume
  restartPolicy: OnFailure
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.azure.com/scalesetpriority"
            operator: In
            values:
            - "spot"